// ============================================
// SNIPPETS.JSX - Code Snippets Page
// ============================================
// This page allows users to:
// - Create new code snippets
// - View all their snippets (collapsed list)
// - Edit existing snippets
// - Delete snippets
// - Search and filter snippets by language/tag
// - Export snippets as Markdown or JSON

import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism'

// Get API base URL from environment variables
const API_BASE = import.meta.env.VITE_API_BASE || ''

// Main Snippets component
// Receives apiHeaders (function) and token from parent (App.jsx)
export default function Snippets({ apiHeaders, token }) {
  const navigate = useNavigate() // Hook to navigate between pages
  
  // ============================================
  // STATE VARIABLES - Store component data
  // ============================================
  
  // List of all snippets fetched from server
  const [snippetsList, setSnippetsList] = useState([])
  
  // Loading state - shows spinner while fetching data
  const [loading, setLoading] = useState(false)
  
  // Success/error messages to display to user
  const [message, setMessage] = useState('')
  
  // Form fields for creating/editing snippets
  const [title, setTitle] = useState('') // Snippet title
  const [code, setCode] = useState('') // The actual code/snippet
  const [language, setLanguage] = useState('') // Programming language
  const [tags, setTags] = useState('') // Comma-separated tags
  const [description, setDescription] = useState('') // Optional description
  
  // Edit mode - stores ID of snippet being edited (null = creating new)
  const [editId, setEditId] = useState(null)
  
  // Search and filter functionality
  const [searchTerm, setSearchTerm] = useState('') // Search input value
  const [filterType, setFilterType] = useState('all') // all, language, or tag
  
  // Expanded snippet ID - which snippet is currently expanded (null = all collapsed)
  const [expandedId, setExpandedId] = useState(null)
  
  // Auto-generation loading states
  const [generatingTitle, setGeneratingTitle] = useState(false)
  const [generatingDescription, setGeneratingDescription] = useState(false)
  const [generatingTags, setGeneratingTags] = useState(false)

  // ============================================
  // AUTO-GENERATE FUNCTIONS - AI-powered field generation
  // ============================================
  
  // Auto-generate title based on code snippet
  async function autoGenerateTitle() {
    if (!code) {
      setMessage('Please enter code snippet first before generating title')
      return
    }
    
    setGeneratingTitle(true)
    setMessage('')
    
    try {
      // Call backend autogen endpoint (to be implemented by other developer)
      const res = await fetch(`${API_BASE}/autogen/title`, {
        method: 'POST',
        headers: apiHeaders(),
        body: JSON.stringify({ content: code, language })
      })
      const data = await res.json()
      
      if (res.ok) {
        setTitle(data.title || data.generated_title || '') // Update title field
        setMessage('Title generated successfully!')
      } else {
        setMessage(data.error || 'Failed to generate title')
      }
    } catch (err) {
      setMessage('Error generating title: ' + err)
    }
    
    setGeneratingTitle(false)
  }
  
  // Auto-generate description based on code snippet
  async function autoGenerateDescription() {
    if (!code) {
      setMessage('Please enter code snippet first before generating description')
      return
    }
    
    setGeneratingDescription(true)
    setMessage('')
    
    try {
      // Call backend autogen endpoint (to be implemented by other developer)
      const res = await fetch(`${API_BASE}/autogen/description`, {
        method: 'POST',
        headers: apiHeaders(),
        body: JSON.stringify({ content: code, language })
      })
      const data = await res.json()
      
      if (res.ok) {
        setDescription(data.description || data.generated_description || '') // Update description field
        setMessage('Description generated successfully!')
      } else {
        setMessage(data.error || 'Failed to generate description')
      }
    } catch (err) {
      setMessage('Error generating description: ' + err)
    }
    
    setGeneratingDescription(false)
  }
  
  // Auto-generate tags based on code snippet
  async function autoGenerateTags() {
    if (!code) {
      setMessage('Please enter code snippet first before generating tags')
      return
    }
    
    setGeneratingTags(true)
    setMessage('')
    
    try {
      // Call backend autogen endpoint (to be implemented by other developer)
      const res = await fetch(`${API_BASE}/autogen/tags`, {
        method: 'POST',
        headers: apiHeaders(),
        body: JSON.stringify({ content: code, language })
      })
      const data = await res.json()
      
      if (res.ok) {
        setTags(data.tags || data.generated_tags || '') // Update tags field
        setMessage('Tags generated successfully!')
      } else {
        setMessage(data.error || 'Failed to generate tags')
      }
    } catch (err) {
      setMessage('Error generating tags: ' + err)
    }
    
    setGeneratingTags(false)
  }

  // ============================================
  // FETCH SNIPPETS - Load data when page loads
  // ============================================
  // useEffect runs after component displays
  // This runs once when component mounts (loads) if token exists
  useEffect(() => {
    if (token && apiHeaders) {
      fetchSnippets() // Call function to get snippets from server
    }
  }, [token]) // Dependency array - run when token changes

  // Function to fetch all snippets from the API
  async function fetchSnippets() {
    if (!apiHeaders) return // Safety check - don't run if no auth headers
    
    setLoading(true) // Show loading spinner
    setMessage('') // Clear any previous messages
    try {
      // Make GET request to fetch snippets
      const res = await fetch(`${API_BASE}/api/v1/snippets`, {
        headers: apiHeaders() // Include authentication token in headers
      })
      
      // Parse response as JSON
      const data = await res.json()
      console.log('Fetched snippets data:', data) // Debug log
      
      // Check if request was successful
      if (res.ok) {
        // API might return array directly or wrapped in object
        const snippetsArray = Array.isArray(data) ? data : (data.snippets || [])
        setSnippetsList(snippetsArray) // Update state with fetched snippets
        console.log('Snippets list set:', snippetsArray) // Debug log
      } else {
        // Request failed - show error message
        setMessage(data.error || 'Failed to fetch snippets')
      }
    } catch (err) {
      // Network error or other exception
      setMessage('Error: ' + err)
    }
    setLoading(false) // Hide loading spinner
  }

  // ============================================
  // CREATE SNIPPET - Add new snippet to database
  // ============================================
  async function createSnippet(e) {
    e.preventDefault() // Prevent form from refreshing page
    setMessage('') // Clear previous messages
    
    // Validate required fields
    if (!title || !code || !language) {
      setMessage('Title, code, and language are required')
      return // Exit function if validation fails
    }

    try {
      // Send POST request to create new snippet
      const res = await fetch(`${API_BASE}/api/v1/snippets`, {
        method: 'POST', // POST = create new resource
        headers: apiHeaders(), // Include authentication token
        // IMPORTANT: Backend expects "snippet" field, not "code"
        body: JSON.stringify({ title, snippet: code, language, tags, description })
      })
      const data = await res.json() // Parse response
      
      if (res.ok) {
        // Success! Show message and clear form
        setMessage('Snippet created successfully!')
        setTitle('') // Clear all form inputs
        setCode('')
        setLanguage('')
        setTags('')
        setDescription('')
        fetchSnippets() // Refresh list to show new snippet
      } else {
        // Failed - show error from server
        setMessage(data.error || 'Failed to create snippet')
      }
    } catch (err) {
      // Network error or exception
      setMessage('Error: ' + err)
    }
  }

  // ============================================
  // UPDATE SNIPPET - Edit existing snippet
  // ============================================
  async function updateSnippet(e) {
    e.preventDefault() // Prevent form refresh
    setMessage('') // Clear messages
    
    // Validate required fields
    if (!title || !code || !language) {
      setMessage('Title, code, and language are required')
      return
    }

    try {
      // Send PATCH request to update snippet
      const res = await fetch(`${API_BASE}/api/v1/snippets`, {
        method: 'PATCH', // PATCH = update existing resource
        headers: apiHeaders(), // Auth token
        // IMPORTANT: Backend expects "snippet" field, not "code"
        body: JSON.stringify({ id: editId, title, snippet: code, language, tags })
      })
      const data = await res.json()
      
      if (res.ok) {
        // Success! Clear form and exit edit mode
        setMessage('Snippet updated successfully!')
        setTitle('') // Clear all inputs
        setCode('')
        setLanguage('')
        setTags('')
        setDescription('')
        setEditId(null)
        fetchSnippets()
        setEditId(null) // Exit edit mode (back to create mode)
        fetchSnippets() // Refresh list with updated snippet
      } else {
        setMessage(data.error || 'Failed to update snippet')
      }
    } catch (err) {
      setMessage('Error: ' + err)
    }
  }

  // ============================================
  // DELETE SNIPPET - Remove snippet from database
  // ============================================
  async function deleteSnippet(id) {
    // Ask user to confirm deletion (prevents accidental deletes)
    if (!confirm('Are you sure you want to delete this snippet?')) return
    
    setMessage('') // Clear messages
    try {
      // Send DELETE request with snippet ID in URL
      const res = await fetch(`${API_BASE}/api/v1/snippets/${id}`, {
        method: 'DELETE', // DELETE = remove resource
        headers: apiHeaders() // Auth token
      })
      const data = await res.json()
      
      if (res.ok) {
        // Success! Show message and refresh list
        setMessage('Snippet deleted successfully!')
        fetchSnippets() // Refresh to show snippet is gone
      } else {
        setMessage(data.error || 'Failed to delete snippet')
      }
    } catch (err) {
      setMessage('Error: ' + err)
    }
  }

  // ============================================
  // EDIT MODE FUNCTIONS
  // ============================================
  
  // Start editing a snippet - populate form with snippet data
  function startEdit(snippet) {
    setEditId(snippet.id) // Set edit mode with this snippet's ID
    setTitle(snippet.title) // Fill in form fields with snippet data
    // Backend might return "snippet" or "code" field - handle both
    setCode(snippet.snippet || snippet.code)
    setLanguage(snippet.language)
    setTags(snippet.tags || '') // Use existing tags or empty string
    setDescription(snippet.description || '') // Use existing description or empty
    window.scrollTo({ top: 0, behavior: 'smooth' }) // Scroll to top to show form
  }

  // Cancel editing - clear form and exit edit mode
  function cancelEdit() {
    setEditId(null) // Exit edit mode (back to create mode)
    setTitle('') // Clear all form fields
    setCode('')
    setLanguage('')
    setTags('')
    setDescription('')
  }

  // ============================================
  // SEARCH SNIPPETS - Find snippets by keyword
  // ============================================
  async function searchSnippets() {
    // If search box is empty, just show all snippets
    if (!searchTerm) {
      fetchSnippets() // Reload all snippets
      return
    }
    
    setLoading(true) // Show spinner
    setMessage('') // Clear messages
    try {
      // Send GET request with search query in URL
      const res = await fetch(`${API_BASE}/api/v1/snippets/search?q=${searchTerm}`, {
        headers: apiHeaders() // Auth token
      })
      const data = await res.json()
      
      if (res.ok) {
        // Success! Display matching snippets
        const snippetsArray = Array.isArray(data) ? data : (data.snippets || [])
        setSnippetsList(snippetsArray)
      } else {
        setMessage(data.error || 'Search failed')
      }
    } catch (err) {
      setMessage('Error: ' + err)
    }
    setLoading(false) // Hide spinner
  }

  // ============================================
  // FILTER SNIPPETS - Filter by language or tag
  // ============================================
  async function filterSnippets() {
    // Validate: user must enter something to filter by
    if (!searchTerm) {
      setMessage('Please enter a filter value')
      return
    }
    
    setLoading(true) // Show spinner
    setMessage('') // Clear messages
    
    try {
      let url = '' // Build URL based on filter type
      if (filterType === 'language') {
        // Filter by programming language: /api/v1/snippets/filter/language/{lang}
        url = `${API_BASE}/api/v1/snippets/filter/language/${searchTerm}`
      } else if (filterType === 'tag') {
        // Filter by tag: /api/v1/snippets/filter/tag/{tagname}
        url = `${API_BASE}/api/v1/snippets/filter/tag/${searchTerm}`
      } else {
        // If 'all' selected, just do regular search
        searchSnippets()
        return
      }
      
      // Send GET request to filter endpoint
      const res = await fetch(url, { headers: apiHeaders() })
      const data = await res.json()
      
      if (res.ok) {
        // Success! Display filtered snippets
        const snippetsArray = Array.isArray(data) ? data : (data.snippets || [])
        setSnippetsList(snippetsArray)
      } else {
        setMessage(data.error || 'Filter failed')
      }
    } catch (err) {
      setMessage('Error: ' + err)
    }
    setLoading(false) // Hide spinner
  }

  // ============================================
  // EXPORT FUNCTIONS - Download snippet as file
  // ============================================
  
  // Export snippet as Markdown file
  async function exportMarkdown(id) {
    // Fetch file with auth headers, then download as blob
    try {
      const res = await fetch(`${API_BASE}/export-snippet-md/v1/${id}`, {
        headers: apiHeaders() // Include auth token
      })
      if (res.ok) {
        const blob = await res.blob() // Get file data
        const url = window.URL.createObjectURL(blob) // Create download URL
        const a = document.createElement('a') // Create download link
        a.href = url
        a.download = `Snippet-${id}.md` // Set filename
        a.click() // Trigger download
        window.URL.revokeObjectURL(url) // Clean up
      } else {
        setMessage('Export failed')
      }
    } catch (err) {
      setMessage('Export error: ' + err)
    }
  }

  // Export snippet as JSON file
  async function exportJSON(id) {
    // Fetch file with auth headers, then download as blob
    try {
      const res = await fetch(`${API_BASE}/export-snippet-json/v1/${id}`, {
        headers: apiHeaders() // Include auth token
      })
      if (res.ok) {
        const blob = await res.blob() // Get file data
        const url = window.URL.createObjectURL(blob) // Create download URL
        const a = document.createElement('a') // Create download link
        a.href = url
        a.download = `Snippet-${id}.json` // Set filename
        a.click() // Trigger download
        window.URL.revokeObjectURL(url) // Clean up
      } else {
        setMessage('Export failed')
      }
    } catch (err) {
      setMessage('Export error: ' + err)
    }
  }

  // ============================================
  // RENDER - Authentication Check
  // ============================================
  
  // If user is not logged in, show message and login button
  if (!token) {
    return (
      <div className="panel">
        <div className="h-title">Authentication Required</div>
        <p>Please login to view and manage your code snippets.</p>
        <button className="btn" onClick={() => navigate('/login')}>Go to Login</button>
      </div>
    )
  }

  // ============================================
  // RENDER - Loading State
  // ============================================
  
  // If data is loading and no snippets shown yet, display loading message
  if (loading && snippetsList.length === 0) {
    return (
      <div className="panel">
        <div className="loading">Loading your snippets...</div>
      </div>
    )
  }

  // ============================================
  // RENDER - Main Page Content (JSX)
  // ============================================
  // JSX = JavaScript XML - looks like HTML but is JavaScript
  
  return (
    <div>
      {/* Form Panel - Create or Edit Snippet */}
      <div className="panel">
        {/* Title changes based on whether we're creating or editing */}
        <div className="h-title">{editId ? 'Edit Snippet' : 'Create New Snippet'}</div>
        
        {/* 
          Form submission:
          - If editId exists, call updateSnippet function
          - If editId is null, call createSnippet function
        */}
        <form onSubmit={editId ? updateSnippet : createSnippet}>
          {/* Language Input - First so it can be used for better autogen */}
          <div className="form-row">
            <label>Language</label>
            <input 
              className="input" 
              value={language} // Controlled input
              onChange={e => setLanguage(e.target.value)} // Update state
              placeholder="e.g. javascript, python, java"
            />
          </div>
          
          {/* Code Textarea - Place early so user enters code before generating other fields */}
          <div className="form-row">
            <label>Code</label>
            <textarea 
              className="input" 
              value={code}
              onChange={e => setCode(e.target.value)}
              placeholder="Paste your code here..."
              rows="8"
            />
            <div className="small muted" style={{ marginTop: '4px' }}>
              💡 Tip: Enter your code first, then use Auto-Generate buttons for title, description, and tags
            </div>
          </div>
          
          {/* Title Input with Auto-Generate Button */}
          <div className="form-row">
            <label>Title</label>
            <div className="input-with-button">
              <input 
                className="input" 
                value={title} // Controlled input - value from state
                onChange={e => setTitle(e.target.value)} // Update state on change
                placeholder="e.g. React useState Hook Example or auto-generate"
              />
              <button 
                className="btn btn-small btn-success" 
                type="button" 
                onClick={autoGenerateTitle}
                disabled={generatingTitle || !code}
                style={{ marginLeft: '8px' }}
              >
                {generatingTitle ? '⏳ Generating...' : '✨ Auto-Generate'}
              </button>
            </div>
          </div>
          
          {/* Description Textarea with Auto-Generate Button */}
          <div className="form-row">
            <label>Description (optional)</label>
            <div className="input-with-button">
              <textarea 
                className="input" 
                value={description} // Controlled input
                onChange={e => setDescription(e.target.value)} // Update state
                placeholder="Brief description of what this code does or auto-generate"
                rows="3"
              />
              <button 
                className="btn btn-small btn-success" 
                type="button" 
                onClick={autoGenerateDescription}
                disabled={generatingDescription || !code}
                style={{ marginLeft: '8px', alignSelf: 'flex-start', marginTop: '4px' }}
              >
                {generatingDescription ? '⏳ Generating...' : '✨ Auto-Generate'}
              </button>
            </div>
          </div>
          
          {/* Tags Input with Auto-Generate Button */}
          <div className="form-row">
            <label>Tags (comma separated)</label>
            <div className="input-with-button">
              <input 
                className="input" 
                value={tags} // Controlled input
                onChange={e => setTags(e.target.value)} // Update state
                placeholder="react, hooks, state or auto-generate"
              />
              <button 
                className="btn btn-small btn-success" 
                type="button" 
                onClick={autoGenerateTags}
                disabled={generatingTags || !code}
                style={{ marginLeft: '8px' }}
              >
                {generatingTags ? '⏳ Generating...' : '✨ Auto-Generate'}
              </button>
            </div>
          </div>
          
          {/* Action Buttons */}
          <div className="flex flex-gap">
            {/* Submit button - text changes based on mode */}
            <button className="btn" type="submit">
              {editId ? 'Update Snippet' : 'Create Snippet'}
            </button>
            
            {/* Cancel button - only show in edit mode */}
            {editId && (
              <button className="btn btn-danger" type="button" onClick={cancelEdit}>
                Cancel Edit
              </button>
            )}
            
            {/* Success/error message display */}
            {message && <div className="small muted">{message}</div>}
          </div>
        </form>
      </div>

      {/* Search & Filter Panel */}
      <div className="panel">
        <div className="h-title">Search & Filter Snippets</div>
        
        {/* Filter Type Dropdown */}
        <div className="form-row">
          <label>Filter Type</label>
          <select 
            className="input" 
            value={filterType} // Current filter type
            onChange={e => setFilterType(e.target.value)} // Update filter type
          >
            {/* Dropdown options */}
            <option value="all">Search All</option>
            <option value="language">Filter by Language</option>
            <option value="tag">Filter by Tag</option>
          </select>
        </div>
        
        {/* Search Bar */}
        <div className="search-bar">
          {/* Search/Filter Input */}
          <input 
            className="input" 
            value={searchTerm} // Search text
            onChange={e => setSearchTerm(e.target.value)} // Update search text
            placeholder={
              // Placeholder text changes based on filter type
              filterType === 'language' ? 'Enter language (e.g. javascript)' :
              filterType === 'tag' ? 'Enter tag (e.g. react)' :
              'Search by title or code...'
            }
            // Allow pressing Enter key to search/filter
            onKeyPress={e => e.key === 'Enter' && (filterType === 'all' ? searchSnippets() : filterSnippets())}
          />
          
          {/* Search/Filter Button */}
          <button className="btn" onClick={filterType === 'all' ? searchSnippets : filterSnippets}>
            {filterType === 'all' ? 'Search' : 'Filter'}
          </button>
          
          {/* Clear Button - reset search and show all snippets */}
          <button className="btn btn-danger" onClick={() => { setSearchTerm(''); fetchSnippets(); }}>
            Clear
          </button>
        </div>
      </div>

      {/* Snippets List Panel */}
      <div className="panel">
        <div className="h-title">My Code Snippets ({snippetsList.length})</div>
        
        {/* Show loading spinner if data is loading */}
        {loading && <div className="loading">Loading snippets...</div>}
        
        {/* Show message if no snippets found */}
        {!loading && snippetsList.length === 0 && (
          <div className="muted">No snippets found. Create your first one!</div>
        )}
        
        {/* 
          Map through snippets and display each one
          .map() creates a list item for each snippet in the array
        */}
        {!loading && snippetsList.map(snippet => {
          // Check if this snippet is currently expanded
          const isExpanded = expandedId === snippet.id
          return (
            <div key={snippet.id} className="item">
              {/* 
                Snippet Header - Clickable to expand/collapse
                Shows title, language badge, and created date
              */}
              <div 
                className="item-header" 
                style={{ cursor: 'pointer' }} // Show pointer cursor on hover
                onClick={() => setExpandedId(isExpanded ? null : snippet.id)} // Toggle expand
              >
                <div>
                  <div className="item-title">
                    {/* Arrow icon changes based on expanded state */}
                    {isExpanded ? '▼' : '▶'} {snippet.title}
                  </div>
                  {/* Language badge - always visible */}
                  <span className="tag">{snippet.language}</span>
                </div>
                <div className="muted small">
                  {/* Format date in readable format */}
                  {new Date(snippet.created_at).toLocaleDateString()}
                </div>
              </div>
              
              {/* 
                Snippet Details - Only show when expanded
                && means "if isExpanded is true, show this"
              */}
              {isExpanded && (
                <>
                  {/* Description (optional) - only show if exists */}
                  {snippet.description && (
                    <div className="item-content" style={{ marginBottom: '8px' }}>
                      {snippet.description}
                    </div>
                  )}
                  
                  {/* Code block - displays the actual code snippet */}
                  <div className="code-block" style={{ margin: '12px 0' }}>
                    <div style={{ 
                      backgroundColor: '#2d2d2d', 
                      padding: '4px 8px', 
                      borderRadius: '4px 4px 0 0',
                      color: '#888',
                      fontSize: '12px',
                      fontFamily: 'monospace'
                    }}>
                      {snippet.language}
                    </div>
                    <SyntaxHighlighter
                      language={snippet.language.toLowerCase()}
                      style={vscDarkPlus}
                      customStyle={{
                        margin: 0,
                        borderRadius: '0 0 4px 4px',
                        fontSize: '14px'
                      }}
                      showLineNumbers={true}
                    >
                      {snippet.snippet || snippet.code}
                    </SyntaxHighlighter>
                  </div>
                  
                  {/* Tags section */}
                  <div className="item-meta">
                    {snippet.tags && (
                      <div>
                        {/* Split tags by comma and display each as a badge */}
                        {snippet.tags.split(',').map((tag, i) => (
                          <span key={i} className="tag">{tag.trim()}</span>
                        ))}
                      </div>
                    )}
                  </div>
                  
                  {/* Action buttons for snippet */}
                  <div className="item-actions" style={{ marginTop: '12px' }}>
                    {/* 
                      Edit button - calls startEdit function
                      e.stopPropagation() prevents click from collapsing snippet
                    */}
                    <button className="btn btn-small" onClick={(e) => { e.stopPropagation(); startEdit(snippet); }}>
                      Edit
                    </button>
                    
                    {/* Export Markdown button */}
                    <button className="btn btn-small btn-success" onClick={(e) => { e.stopPropagation(); exportMarkdown(snippet.id); }}>
                      Export MD
                    </button>
                    
                    {/* Export JSON button */}
                    <button className="btn btn-small btn-success" onClick={(e) => { e.stopPropagation(); exportJSON(snippet.id); }}>
                      Export JSON
                    </button>
                    
                    {/* Delete button - removes snippet from database */}
                    <button className="btn btn-small btn-danger" onClick={(e) => { e.stopPropagation(); deleteSnippet(snippet.id); }}>
                      Delete
                    </button>
                  </div>
                </>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
